# permissions for end users to view instancehas.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: instanceha-viewer-role
rules:
- apiGroups:
  - instanceha.openstack.org
  resources:
  - instancehas
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - instanceha.openstack.org
  resources:
  - instancehas/status
  verbs:
  - get
