apiVersion: network.openstack.org/v1beta1
kind: DNSMasq
metadata:
  labels:
    app.kubernetes.io/name: dnsmasq
    app.kubernetes.io/instance: dnsmasq-sample
    app.kubernetes.io/part-of: infra-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: infra-operator
  name: dnsmasq-sample
spec:
  # TODO(user): Add fields here
