apiVersion: network.openstack.org/v1beta1
kind: DNSMasq
metadata:
  name: dnsmasq
spec:
  containerImage: quay.io/tripleozedcentos9/openstack-neutron-server:current-tripleo
  externalEndpoints:
  - ipAddressPool: ctlplane
    loadBalancerIPs:
    - 192.168.122.80
  replicas: 1
  options:
  - key: server
    values:
    - 10.11.5.19
  - key: server
    values:
    - 10.2.32.1
  debug:
    service: false
