apiVersion: network.openstack.org/v1beta1
kind: IPSet
metadata:
  name: edpm-compute-1
spec:
  hostname: edpm-compute-1
  networks:
  - name: CtlPlane
    subnetName: subnet1
  - name: InternalApi
    subnetName: subnet1
  - name: Storage
    subnetName: subnet1
  - name: Tenant
    subnetName: subnet1
